# Deferred evaluation

(Example from [Advanced R](http://adv-r.had.co.nz/Performance.html#faster-r))

Justin Talbot, the author of Riposte, points out:

> for long vectors, R's execution is completely memory bound. It
> spends almost all of its time reading and writing vector
> intermediates to memory.

If we could eliminate these intermediate vectors, we could improve
performance and reduce memory usage.

In the following example, 1 million values in `x` and `y` are added,
while only half of them (those where `z` is `TRUE`) are eventually
summed. This approach creates a temporary vector `x + y` of length 1
million (which is then subset with `z`) to be stored in memory, and as
many accessed to memory to copy data to the CPU.

```{r, eval=FALSE}
x <- runif(1e6)
y <- runif(1e6)
z <- sample(c(TRUE, FALSE), 1e6, rep = TRUE)
sum((x + y)[z])
```

An alternative approach, shown below using R syntax, would be to sum
only the elements of `x` and `y` that match a `z == TRUE`.

```
res <- 0
for (i in 1:length(x)) {
   if (z[i])
      res <- res + x[i] + y[i]
}
```

The goal of *deferred evaluation* is to perform such transformation
automatically.

### Exercise

The vectorised R code above is of course very fast, making use of fast
vectorised operations implemeted in C, and re-implementing the
deferred evaluation in R is likely slower. 

- If this was a crucial chunk that was to be run many times,
  implementing the deferred version in C++ using Rcpp could be
  beneficial. Write and benchmark different R and C++ implementations.

- Make sure that the C++ and R results are identical.


