 
\SweaveOpts{engine=R,eps=FALSE}
\SweaveOpts{echo=TRUE,eval=TRUE,fig=FALSE,results=verbatim,cache=FALSE,tikz=TRUE,external=FALSE,prefix.string=sweave-cache/fig}

\documentclass{beamer}
% Setup appearance:
% \usetheme{Darmstadt}
\usefonttheme[onlylarge]{structurebold}

\setbeamerfont*{frametitle}{size=\normalsize,series=\bfseries}
\setbeamertemplate{navigation symbols}{}
% Standard packages
% \usepackage[english]{babel}
% \usepackage[latin1]{inputenc}
% \usepackage{times}
% \usepackage[T1]{fontenc}
\usepackage{Sweave}
\usepackage{ulem}
\usepackage{colortbl}
% Setup TikZ
\usepackage{tikz}
\usetikzlibrary{arrows}
\tikzstyle{block}=[draw opacity=0.7,line width=1.4cm]
% \usecolortheme{seagull}
\usecolortheme{default}

%% new commande
\let\code=\texttt
\let\proglang=\textsf

\newcommand{\R}{\texttt{R} }
\newcommand{\Rfunction}[1]{{\texttt{#1}}}
\newcommand{\Robject}[1]{{\texttt{#1}}}
\newcommand{\Rpackage}[1]{{\mbox{\normalfont\textsf{#1}}}}
\newcommand{\email}[1]{\href{mailto:#1}{\normalfont\texttt{#1}}}
%% colors
\definecolor{Red}{rgb}{0.7,0,0}
\definecolor{Blue}{rgb}{0,0,0.8}

\hypersetup{%
  hyperindex = {true},
  colorlinks = {true},
  linktocpage = {true},
  plainpages = {false},
  linkcolor = {Blue},
  citecolor = {Blue},
  urlcolor = {Red},
  pdfstartview = {Fit},
  pdfpagemode = {UseOutlines},
  pdfview = {XYZ null null null}
}

% Author, Title, etc.
\title[CSAMA 2012 -- Brixen] 
{%
  R Basics
}

\author[L. Gatto]
{
  Laurent Gatto \\
  \scriptsize \url{lg390@cam.ac.uk}
}

%% \institute[CCP]
%% {
%% %   \inst{1}%
%%   Cambridge System Biology Centre\\
%%   University of Cambridge \\
%% }

\date[2/07/2012]
{
  Computational Statistics for Genome Biology\\
  2$^{nd}$ July 2012
}


\pgfdeclareimage[height=.7cm]{uc-logo}{./Figures/uc-logo}
\pgfdeclareimage[height=.7cm]{ebi-logo}{./Figures/EMBLEBIlogo}
% \logo{\pgfuseimage{uc-logo}}


\AtBeginSection[] % Do nothing for \section*
{
\begin{frame}<beamer>
\frametitle{Plan}
\tableofcontents[currentsection]
\end{frame}
}


% The main document

\begin{document}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Title frame                                                 %% 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{frame}
  \titlepage
\end{frame}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Table of contents                                           %% 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{frame}{Plan}
  \footnotesize
  \tableofcontents
\end{frame}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% section                                                     %% 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

<<echo=FALSE>>=
library(Biobase)
data(sample.ExpressionSet)
@ 

\input{Sec-Intro.tex}

\input{Sec-DataTypes.tex}

\input{Sec-Manip.tex}

\input{Sec-Useful.tex}

\input{Sec-Plotting.tex}

\input{Sec-Programming.tex}

\input{Sec-Packages.tex}

%% \input{Sec-RBioc.tex}



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% section                                                     %% 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{frame}
  \begin{block}{References}
    \begin{itemize}
    \item W. N. Venables, D. M. Smith and the R Development Core Team, 
      An Introduction to R (get it with \Rfunction{help.start()})
    \item R. Gentleman, R Programming for Bioinformatics, CRC Press, 2008
    \end{itemize}    
  \end{block}
\end{frame}

%%\vspace{5cm}
\begin{frame}[fragile]
<<sessioninfo, results=tex>>=
toLatex(sessionInfo())
@   
\end{frame}

\begin{frame}
  \vspace{2cm}
  \begin{center}
  Thank you for your attention    
  \end{center}
\end{frame}

\end{document}
