* Refactoring the basic R course/slides

- Identify independent parts of the course
- Decide which ones should be kept as is, updated, re-written from scratch, dropped

LG: The stats bit at the end of day 1 could be dropped, or at least heavily reduced.

LG: The graphics part (end od day 2) should be imporved, IMHO. They learn some intuitive plotting through the exercises. I would suggest to build uppon that throughout the coures, use the plotting part to summerise/formalise and possibly illustrate a bit of ggplot2 (and/or lattice). There is every now and then somebody that comes and asks about ggplot2, and base graphics, at least how it is taught now, does not give proper credit to plotting using R. I don't mean to teach the ggplot2 dialect, but at least mention it and produce nice plots using base graphics.

Missing from the plotting part: 
- (good usage of) legends, smoothscatter, identify

LG: In general, the exercises are good and useful, but I'm quite unhappy with some of the solutions. Some of the code is not beautiful - the code must be understandable for beginners, of course, but we should make sure that we show clean straight-to-the-point code.

RF: I think in the first morning, the number of different objects comes too thick and fast to be understood by a significant number. I think a couple of exercises in which students are encouraged to manipulate, say, vectors and matrices, should then be followed by the discussion on, and perhaps an exercise on data frames. After this perhaps reading in data and a more natural discussion of factors with a good example.

RF: The storage types and methods is too involved. Could be done with a quick discussion of data types and point to the is. functions.

RF: I agree that the stats bit at the end of Day 1 should be slimmed down, but not dropped.

RF: The Day 2 colonies example, I have always felt, gets lost in the convoluted set up of the 'experiment'. Perhaps this, or a similar example could be built up more gradually.

RF: I agree with LG that the graphics afternoon is really a kind of lecture, and a bit boring. Perhaps keep one or two of the examples (I think the 2nd axis example covers a lot). I was actually asked on Tuesday by two people who wanted to know about ggplot, so maybe a brief example about building up such a plot would be worthwhile. 
