 \documentclass{beamer}
% Setup appearance:
% \usetheme{Darmstadt}
\usefonttheme[onlylarge]{structurebold}

\setbeamerfont*{frametitle}{size=\normalsize,series=\bfseries}
\setbeamertemplate{navigation symbols}{}
% Standard packages
% \usepackage[english]{babel}
% \usepackage[latin1]{inputenc}
% \usepackage{times}
% \usepackage[T1]{fontenc}
\usepackage{ulem}
\usepackage{colortbl}
% Setup TikZ
\usepackage{tikz}
\usetikzlibrary{arrows}
\tikzstyle{block}=[draw opacity=0.7,line width=1.4cm]
% \usecolortheme{seagull}
\usecolortheme{default}

%% new commande
\let\code=\texttt
\let\proglang=\textsf

\newcommand{\R}{\texttt{R} }
\newcommand{\Rfunction}[1]{{\texttt{#1}}}
\newcommand{\Robject}[1]{{\texttt{#1}}}
\newcommand{\Rpackage}[1]{{\mbox{\normalfont\textsf{#1}}}}
\newcommand{\email}[1]{\href{mailto:#1}{\normalfont\texttt{#1}}}
%% colors
\definecolor{Red}{rgb}{0.7,0,0}
\definecolor{Blue}{rgb}{0,0,0.8}

\hypersetup{%
  hyperindex = {true},
  colorlinks = {true},
  linktocpage = {true},
  plainpages = {false},
  linkcolor = {Blue},
  citecolor = {Blue},
  urlcolor = {Red},
  pdfstartview = {Fit},
  pdfpagemode = {UseOutlines},
  pdfview = {XYZ null null null}
}

% Author, Title, etc.
\title%%[CSAMA 2012 -- Brixen] 
{%
  Quick \R Package 
}

\author[L. Gatto]
{
  Laurent Gatto \\
  \scriptsize \url{lg390@cam.ac.uk}
}

%% \institute[CCP]
%% {
%% %   \inst{1}%
%%   Cambridge System Biology Centre\\
%%   University of Cambridge \\
%% }

\date[2/07/2012]
{
  Computational Statistics for Genome Biology\\
  28$^{th}$ June 2013
}


\pgfdeclareimage[height=.7cm]{uc-logo}{./Figures/uc-logo}
\pgfdeclareimage[height=.7cm]{ebi-logo}{./Figures/EMBLEBIlogo}
% \logo{\pgfuseimage{uc-logo}}


\AtBeginSection[] % Do nothing for \section*
{
\begin{frame}<beamer>
\frametitle{Plan}
\tableofcontents[currentsection]
\end{frame}
}


% The main document

\begin{document}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Title frame                                                 %% 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{frame}
  \titlepage
\end{frame}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Table of contents                                           %% 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% \begin{frame}{Plan}
%%   \footnotesize
%%   \tableofcontents
%% \end{frame}

<<knitr, cache=FALSE, echo=FALSE>>=
library("knitr")
options(width = 60)
opts_chunk$set(prompt = TRUE,
               comment = '',
               fig.align = 'center')
@ %% $


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% section                                                     %% 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{frame}
  \begin{block}{Overview}
    We are about to create the \Rpackage{QuickPackage} \R package:
    \begin{enumerate}
    \item Create a dummy function to come into the package
    \item Create the package structure
    \item Update the package content
    \item Build/check/install
    \item Enjoy!
    \end{enumerate}
  \end{block}
\end{frame}

\begin{frame}[fragile]
<<dummy, tidy=FALSE>>=
## This is the dummy function that will return
## information about our 'QuickPackage'
qpf <- function() 
  packageDescription("QuickPackage")
@   
\end{frame}

\begin{frame}[fragile]
<<pgkskel>>=
## This creates the package template
package.skeleton("QuickPackage", list = c("qpf"))
@ 
\end{frame}

\begin{frame}[fragile]
  \Rpackage{QuickPackage} structure:
\begin{verbatim}
QuickPackage/
|-- DESCRIPTION
|-- man
|   |-- qpf.Rd
|   `-- QuickPackage-package.Rd
|-- NAMESPACE
|-- R
|   `-- qpf.R
`-- Read-and-delete-me
\end{verbatim}
\end{frame}

\begin{frame}
  \begin{itemize}
  \item Read and delete \texttt{Read-and-delete-me}
  \item Update \texttt{DESCRIPTION}
  \item Write a proper package documentation file or delete it (this is the only optional documentation) and 
    update the man page for \Rfunction{qpf} (see next slide)
  \end{itemize}
\end{frame}

\begin{frame}[fragile]
  \begin{small}  
\begin{verbatim}
\name{qpf}
\alias{qpf}
\title{ A test function }
\description{
  Returns package information.
}
\usage{
qpf()
}
\value{
An object of class \code{packageDescription}.
}
\examples{
qpf()
}
\end{verbatim}
  \end{small}
\end{frame}


\begin{frame}
  In a terminal:
  \begin{enumerate}
  \item Build the package with \\
    \Rfunction{R CMD build QuickPackage}
  \item Check the package with \\
    \Rfunction{R CMD check QuickPackage\_1.0.tar.gz}
  \item If any, fix errors and warnings and repeat steps 1 and 2.
  \item Install the package with \\
    \Rfunction{R CMD INSTALL QuickPackage\_1.0.tar.gz}
  \end{enumerate}
\end{frame}

<<clean, echo=FALSE>>=
rm(list=ls())
system("rm ./QuickPackage_1.0.tar.gz")
system("rm ./QuickPackage/Read-and-delete-me")
system("rm ./QuickPackage/man/QuickPackage-package.Rd")
system("cp files/qpf.Rd QuickPackage/man/.")
system("cp files/DESCRIPTION QuickPackage/.")
system("R CMD build QuickPackage")
system("R CMD check QuickPackage_1.0.tar.gz")
system("R CMD INSTALL QuickPackage_1.0.tar.gz")
@ 

\begin{frame}[fragile]
<<enjoy>>=
library("QuickPackage")
qpf()
@   
\end{frame}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% section                                                     %% 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{frame}
  \begin{block}{References}
    \begin{itemize}
    \item \R package development, Robert Stojnic and Laurent Gatto
      \url{https://github.com/lgatto/RPackageDevelopment} \\
    \item Writing R Extensions,  R Development Core Team, 
      (get it with \Rfunction{help.start()})
    \item This work is licensed under a CC BY-SA 3.0 License.
    \item Course web page and more material: \url{https://github.com/lgatto/TeachingMaterial}
    \end{itemize}    
  \end{block}
\end{frame}

%%\vspace{5cm}
\begin{frame}[fragile]
<<sessioninfo, results='asis'>>=
toLatex(sessionInfo())
@   
\end{frame}

<<echo=FALSE>>=
system("R CMD REMOVE QuickPackage")
@ 


\end{document}
