#! /usr/local/bin/Rscript

args <- commandArgs(TRUE)

if (length(args) == 0) {
  message("Provide at least one 'Rmd' file as argument")
  q()
}

library(knitr)

for (rmd in args) {
  # purl(rmd) # extract R-Code with chunk headers
  knit(rmd, tangle = TRUE) # without chunk headers
  knit2html(rmd)
}
## unlink(sub("\\.Rmd$", ".md", args))

q()
